### ISSUE TITLE
Please add LICENSE file

### ISSUE THREAD

**Issue by arcturusannamalai** [mayooresan/Android-TamilUtil#2]
Vanakkam Mayooresan; thanks for sharing your code. It would be great to have this piece as part of open-tamil project, and if you can add a LICENSE (MIT/Apache preferably) we can have this done.
Thanks again.
-Muthu

**Comment by mayooresan** [comment]
Added the [license](https://github.com/mayooresan/Android-TamilUtil/blob/master/LICENSE)
